# Generated by Django 5.1.7 on 2025-03-26 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expenseId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
